require: rubocop-rspec

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
AllCops:
  Exclude:
  - 'spec/rails_helper.rb'
  - 'spec/spec_helper.rb'
  - 'db/schema.rb'
  - 'db/seeds.rb'
  - 'db/migrate/**.rb'